name: CI with Postman CLI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/GoREST Test Collection.json" -e "32182428-8d3c775d-71cf-4fe9-9524-ff9957b5a382" --integration-id "156014-${{ github.run_id }}"
          # Lint your API using Postman CLI
          # postman api lint 26aab39e-e320-4959-820a-02883e94ebba --integration-id 156014
          
      - name: Publish JUnit Cucumber Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: ./target/junit-cucumber-results.xml
